name: E2E test

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Add explicit timeout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        
      - name: Install Chrome dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          
      - name: Cache Puppeteer binaries
        uses: actions/cache@v3
        id: puppeteer-cache
        with:
          path: |
            tests/node_modules/puppeteer/.local-chromium
          key: ${{ runner.os }}-puppeteer-${{ hashFiles('tests/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-puppeteer-

      - name: Install Puppeteer
        if: steps.puppeteer-cache.outputs.cache-hit != 'true'
        run: |
          cd tests
          npm install puppeteer
            
      - name: Install dependencies
        run: |
          cd tests
          npm ci
        
      - name: Run tests
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: |
          cd tests 
          npm run test