name: Release
on:
  push:
    branches:
      - develop
permissions:
  id-token: write
  contents: read
jobs:
  update_pull_request:
    timeout-minutes: 10
    runs-on: [self-hosted, organization]
    steps:
      - id: own_repository_write_credentials
        uses: lifull-growth/configure-github-credentials@v0
        with:
          role: OwnRepositoryWrite
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          GITHUB_SHA_BEFORE=$(cat ${GITHUB_EVENT_PATH} | jq -r .before)
          echo "revision=$(git rev-parse origin/master)" >> $GITHUB_OUTPUT
          echo "diff=$(git log origin/master..HEAD | grep 'Merge pull request' | jq -Rs .)" >> $GITHUB_OUTPUT
          echo "step=$(git log ${GITHUB_SHA_BEFORE}..${GITHUB_SHA} | grep 'Merge pull request' | jq -Rs .)" >> $GITHUB_OUTPUT
        id: master
      - uses: actions/github-script@v7
        with:
          github-token: ${{ steps.own_repository_write_credentials.outputs.token }}
          script: |
            const diff = `${{ fromJSON(steps.master.outputs.diff) }}`;
            await github.rest.pulls.list({ owner: context.repo.owner, repo: context.repo.repo, base: 'master', head: '${{ github.repository_owner }}:develop', state: 'open' }).then((response) => {
              const revision = `${{ steps.master.outputs.revision }}`;
              if (response.data.length > 0) {
                const pull = response.data[0];
                return github.rest.pulls.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: pull.number,
                  body: `
            前回のRevision: ${revision}

            また、Update branchボタンを押すと \`master\` ブランチ上のMerge Commitが \`develop\` ブランチに取り込まれてコミットログが汚れてしまいます。
            GitHub Actionsによる全てのCheckを通過するとUpdate branchボタンを押すことなくMergeできます。

            ${diff.split("\n").filter((s) => { return s !== "" }).map((s) => { return `- ${s.trim()}` }).join("\n")}
            `,
                }).then(() => pull.number)
              }
              return github.rest.pulls.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                base: 'master',
                head: 'develop',
                title: '[Release from test, pool to production] develop => master',
                body: `
            前回のRevision: ${revision}

            また、Update branchボタンを押すと \`master\` ブランチ上のMerge Commitが \`develop\` ブランチに取り込まれてコミットログが汚れてしまいます。
            GitHub Actionsによる全てのCheckを通過するとUpdate branchボタンを押すことなくMergeできます。

            ${diff.split("\n").filter((s) => { return s !== "" }).map((s) => { return `- ${s.trim()}` }).join("\n")}
            `,
              }).then((response) => response.data.number)
            }).then((num) => {
              const step = `${{ fromJSON(steps.master.outputs.step) }}` || diff;
              return github.rest.issues.createComment({
                issue_number: num,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `
            前回からの差分チェック
            ${step.split("\n").filter((s) => { return s !== "" }).map((s) => { return `- [ ] ${s.trim()}` }).join("\n")}
            `,
              })
            })
