name: Detect RepositorySettings updates
on:
  merge_group:
    types: [checks_requested]
  pull_request:
    branches:
      - develop
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review
env:
  # use embedded GITHUB_TOKEN https://docs.github.com/ja/actions/reference/authentication-in-a-workflow#
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  repository-settings:
    timeout-minutes: 10
    runs-on: [self-hosted, organization]
    if: github.event.pull_request.state == 'open'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
        if: contains(github.event.pull_request.labels.*.name, 'ActionRequired:RepositorySettings') != true
      # `on.pull_request.paths` does not hook file creation
      - run: |
          if git diff origin/${{ github.event.pull_request.base.ref }} HEAD --name-only --diff-filter=d | grep -E '^bin/repository-settings.sh$'; then
            echo "continue=1" >> $GITHUB_OUTPUT
          else
            echo "continue=0" >> $GITHUB_OUTPUT
          fi
        id: check
        if: contains(github.event.pull_request.labels.*.name, 'ActionRequired:RepositorySettings') != true
      - run: |
          curl -sSL -X POST -H "Authorization: token ${GITHUB_TOKEN}" -d "{\"labels\":[\"ActionRequired:RepositorySettings\"]}" ${{ github.event.pull_request.issue_url }}/labels
        if: steps.check.outputs.continue == '1' && contains(github.event.pull_request.labels.*.name, 'ActionRequired:RepositorySettings') != true
      - run: |
          body=$(cat <<EOS
          repository-settings.shが修正されました。
          このPullRequestの **Merge後** に[リポジトリ設定の更新](${{ github.event.repository.html_url }}/blob/HEAD/keel.md#リポジトリ設定の更新)を実行する必要があります。
          EOS
          )
          curl -sSL -X POST -H "Authorization: token ${GITHUB_TOKEN}" -d "$(jq -n --arg body "$body" '{$body}')" ${{ github.event.pull_request.comments_url }}
        if: steps.check.outputs.continue == '1' && contains(github.event.pull_request.labels.*.name, 'ActionRequired:RepositorySettings') != true && (github.event.pull_request.base.ref == 'develop' || github.event.pull_request.base.ref == 'master')
