name: Lint for Dockerfile
on:
  merge_group:
    types: [checks_requested]
  pull_request:
    branches:
      - develop
      - master
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review
env:
  # use embedded GITHUB_TOKEN https://docs.github.com/ja/actions/reference/authentication-in-a-workflow#
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DOCKER_BUILDKIT: 1
  IMAGE_TAG: test
  IMAGE_CACHE_DIR: /tmp/cache/docker-image
  REVIEWDOG_CACHE_DIR: /tmp/cache/reviewdog
  HADOLINT_CACHE_DIR: /tmp/cache/hadolint
jobs:
  hadolint:
    timeout-minutes: 10
    runs-on: [self-hosted, organization]
    if: github.event.pull_request.draft == false && github.event.pull_request.state == 'open'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # `on.pull_request.paths` does not hook file creation
      - run: |
          if git diff origin/${{ github.event.pull_request.base.ref }} HEAD --name-only --diff-filter=d | grep -E '^(Dockerfile)$'; then
            echo "continue=1" >> $GITHUB_OUTPUT
          else
            echo "continue=0" >> $GITHUB_OUTPUT
          fi
        id: check
      - name: Cache reviewdog
        uses: actions/cache@v3
        id: reviewdog_cache
        with:
          path: ${{ env.REVIEWDOG_CACHE_DIR }}
          key: ${{ runner.os }}-reviewdog-0.15.0
        if: steps.check.outputs.continue == '1'
      - name: Install reviewdog
        if: steps.check.outputs.continue == '1' && steps.reviewdog_cache.outputs.cache-hit != 'true'
        run: |
          wget https://raw.githubusercontent.com/reviewdog/reviewdog/v0.15.0/install.sh -O - | sh -s -- -b "${REVIEWDOG_CACHE_DIR}"
      - name: Cache hadolint
        uses: actions/cache@v3
        id: hadolint_cache
        with:
          path: ${{ env.HADOLINT_CACHE_DIR }}
          key: ${{ runner.os }}-hadolint-1.23.0
        if: steps.check.outputs.continue == '1'
      - name: Install hadolint
        if: steps.check.outputs.continue == '1' && steps.hadolint_cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p "${HADOLINT_CACHE_DIR}"
          wget "https://github.com/hadolint/hadolint/releases/download/v1.23.0/hadolint-Linux-x86_64" -O "${HADOLINT_CACHE_DIR}/hadolint"
          chmod +x "${HADOLINT_CACHE_DIR}/hadolint"
      - name: hadolint(Dockerfile)
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          "${HADOLINT_CACHE_DIR}/hadolint" Dockerfile | ./bin/runbook-translator hadolint | "${REVIEWDOG_CACHE_DIR}/reviewdog" -efm='%f:%l DL%n\ %t%*[^:]:\ %m' -reporter=github-pr-review -fail-on-error=true
        if: steps.check.outputs.continue == '1'
