name: Renovate keelctl
on:
  schedule:
    # UTC
    - cron: '0 0 * * 1-5'
  workflow_dispatch:
    inputs: {}
permissions:
  id-token: write
  contents: read
jobs:
  renovate:
    timeout-minutes: 10
    runs-on: [self-hosted, organization]
    steps:
      - id: own_repository_write_credentials
        uses: lifull-growth/configure-github-credentials@v0
        with:
          role: OwnRepositoryWrite
      - id: generate_keelctl_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.KEEL_AUTOMATION_LIFULL_GHAPP_ID }}
          private-key: ${{ secrets.KEEL_AUTOMATION_LIFULL_GHAPP_PRIVATE_KEY }}
          owner: lifull
          repositories: keelctl,v1clusterbootstrap
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.own_repository_write_credentials.outputs.token }}
      - id: keelctl_gen
        run: |
          git config --global user.email "keel@lifull.com"
          git config --global user.name "keel"

          mkdir -p /opt/actions-runner/_work/_temp/keelctl/bin
          url=$(curl -s -H "Authorization: Bearer ${{ steps.generate_keelctl_token.outputs.token }}" https://api.github.com/repos/lifull/keelctl/releases/latest | jq -r '.assets[] | select(.name | startswith("keelctl") and contains("linux_amd64")) | .url')
          if [ -z $url ]; then
            exit 0
          fi
          keelctl_asset_id=$(basename $url)
          wget --auth-no-challenge --header="Accept:application/octet-stream" -O /opt/actions-runner/_work/_temp/keelctl/bin/keelctl https://x-access-token:${{ steps.generate_keelctl_token.outputs.token }}@api.github.com/repos/lifull/keelctl/releases/assets/$keelctl_asset_id
          chmod +x /opt/actions-runner/_work/_temp/keelctl/bin/keelctl
          export PATH=$PATH:/opt/actions-runner/_work/_temp/keelctl/bin

          GITHUB_TOKEN="${{ steps.generate_keelctl_token.outputs.token }}" bin/keelctl gen keel_configuration.yaml . --yes --no-push

          if git diff --exit-code; then
            echo "continue=0" >> $GITHUB_OUTPUT
          else
            git add .
            if git commit -m "chore: update to the latest keelctl"; then
              git push -f origin HEAD:feature/develop-renovate-keelctl

              echo "continue=1" >> $GITHUB_OUTPUT
            fi
          fi
      - uses: actions/github-script@v7
        with:
          github-token: ${{ steps.own_repository_write_credentials.outputs.token }}
          script: |
            await github.rest.pulls.list({ owner: context.repo.owner, repo: context.repo.repo, base: 'develop', head: '${{ github.repository_owner }}:feature/develop-renovate-keelctl', state: 'open' }).then((response) => {
              if (response.data.length > 0) {
                return
              }
              return github.rest.pulls.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                base: 'develop',
                head: '${{ github.repository_owner }}:feature/develop-renovate-keelctl',
                title: '[Renovate keelctl] Update to the latest keelctl',
                body: `
            \`bin/keelctl gen keel_configuration.yaml . --yes --no-push\` を実行して最新のkeelctlにアップデートしました。
            [リリースノート](https://github.com/lifull/keelctl/releases)を確認した上でしかるべき対応をしてMergeしてください。
            `,
              })
            })
        if: steps.keelctl_gen.outputs.continue == '1'
