name: Labeler
on:
  merge_group:
    types: [checks_requested]
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  auto_labeling:
    timeout-minutes: 10
    runs-on: [self-hosted, organization]
    steps:
      - uses: actions/labeler@v4
        if: github.actor != 'dependabot[bot]'
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml
          sync-labels: true
