name: Control test Ephemeral Environment
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - closed
env:
  # use embedded GITHUB_TOKEN https://docs.github.com/ja/actions/reference/authentication-in-a-workflow#
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ACTION_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
jobs:
  about_ephemeral_environment:
    timeout-minutes: 10
    runs-on: [self-hosted, organization]
    if: github.event.pull_request.state == 'open' && startsWith(github.event.pull_request.head.ref, 'feature/') && contains(github.event.pull_request.labels.*.name, 'EphemeralEnvironment') != true
    steps:
      - run: |
          body=$(cat <<EOS
          このPullRequestはEphemeralEnvironmentの対象です。
          詳しくは[EphemeralEnvironmentについて](${{ github.event.repository.html_url }}/blob/HEAD/keel.md#EphemeralEnvironmentについて)をご覧ください。

          再デプロイするためには[こちら](${ACTION_URL})から `Deploy Ephemeral Environment` のRe-runを実行してください。

          ---
          要: [IAMユーザの発行](https://github.com/lifull/V1ClusterBootstrap/blob/develop/docs/keelize/permission.md#iam%E3%83%A6%E3%83%BC%E3%82%B6%E3%81%AE%E7%99%BA%E8%A1%8C), \`awscliv2\`, \`jq\`

          以下のコマンドを実行して出力されたURLからEphemeralEnvironmentの最新のビルドステータスを確認することができます。
          \`\`\`
          $ aws cloudformation describe-stacks --stack-name machimusubi-web-test | jq -r '.Stacks[].Outputs[] | select(.OutputKey == "Build").OutputValue' | xargs aws codebuild list-builds-for-project --max-items 20 --project-name | jq -r '.ids | join(" ")' | xargs aws codebuild batch-get-builds --ids | jq -r '.builds | map(select(.sourceVersion == "${{ github.event.pull_request.number }}")) | .[0] | "https://ap-northeast-1.console.aws.amazon.com/codesuite/codebuild/projects/"+.projectName+"/build/"+.id'
          \`\`\`

          また、以下のコマンドを実行することで最新のEphemeralEnvironmentのビルドログを \`tail -f\` のように確認することもできます。
          \`\`\`
          $ eval \$(aws cloudformation describe-stacks --stack-name machimusubi-web-test | jq -r '.Stacks[].Outputs[] | select(.OutputKey == "Build").OutputValue' | xargs aws codebuild list-builds-for-project --max-items 20 --project-name | jq -r '.ids | join(" ")' | xargs aws codebuild batch-get-builds --ids | jq -r '.builds | map(select(.sourceVersion == "${{ github.event.pull_request.number }}")) | .[0].logs | "aws logs tail --follow --since 1h "+.groupName+" --log-stream-names "+.streamName')
          \`\`\`
          EOS
          )
          data=$(jq -n --arg body "${body}" '{$body}')
          curl -sSL -X POST -H "Authorization: token ${GITHUB_TOKEN}" -d "$data" ${{ github.event.pull_request.comments_url }}
          curl -sSL -X POST -H "Authorization: token ${GITHUB_TOKEN}" -d "{\"labels\":[\"EphemeralEnvironment\"]}" ${{ github.event.pull_request.issue_url }}/labels
  deploy_ephemeral_environment:
    timeout-minutes: 10
    runs-on: [self-hosted, organization]
    if: github.event.pull_request.state == 'open' && startsWith(github.event.pull_request.head.ref, 'feature/')
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.TEST_PUBLIC_BUILD_USER_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.TEST_PUBLIC_BUILD_USER_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - run: |
          aws codebuild start-build --project-name ${{ secrets.TEST_PUBLIC_BUILD_PROJECT_NAME }} --source-version ${{ github.event.pull_request.number }}
  revert_ephemeral_environment:
    timeout-minutes: 10
    runs-on: [self-hosted, organization]
    if: github.event.action == 'closed' && startsWith(github.event.pull_request.head.ref, 'feature/')
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.TEST_PUBLIC_BUILD_USER_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.TEST_PUBLIC_BUILD_USER_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - run: |
          aws codebuild start-build --project-name ${{ secrets.TEST_PUBLIC_BUILD_PROJECT_NAME }} --source-version ${{ github.event.pull_request.number }} --environment-variables-override name=REVERT,value=true
