name: 'Label stale issues and PRs'
on:
  schedule:
    - cron: '30 18 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          days-before-stale: 30
          days-before-close: -1
          stale-issue-message: '30日以上アクティビティがない為「stale」ラベルを付与しました。残し続けたいissue/prの場合はラベルを削除してください。（現在は無効ですがラベルがある状態で7日以上アクティビティがない場合にCloseされます。）'
          stale-pr-message: '30日以上アクティビティがない為「stale」ラベルを付与しました。残し続けたいissue/prの場合はラベルを削除してください。（現在は無効ですがラベルがある状態で7日以上アクティビティがない場合にCloseされます。）'
